name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main      # main 브랜치에 푸시될 때
      - develop   # develop 브랜치에도 자동 배포를 원하면 추가

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        working-directory: joongna_gazua/joongna_gazua_flutter
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: joongna_gazua/joongna_gazua_flutter
        run: flutter build web --base-href="/joongna_gazua/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: joongna_gazua/joongna_gazua_flutter/build/web
